name: Alerta BTC cada minuto

on:
  schedule:
    - cron: '* * * * *'  # ejecuta cada minuto
  workflow_dispatch:  # permite ejecutar manualmente

jobs:
  alerta-minuto:
    runs-on: ubuntu-latest
    env:  # aqu√≠ referenciamos los secrets
      TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Chequear repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar alerta
        run: python alerta.py
